version: "3.8"
name: "python-api-poc"
services:
    db:
        image: mysql:8.0.21
        container_name: db
        platform: linux/x86_64
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=database
        restart: "always"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 10s
            retries: 5
        cap_add:
            - SYS_NICE
